-- ENUM Types for dropdowns
CREATE TYPE user_type_enum AS ENUM ('student', 'teacher', 'librarian','guest');
CREATE TYPE user_status_enum AS ENUM ('active', 'inactive', 'banned');
CREATE TYPE storage_type_enum AS ENUM ('online', 'offline');
CREATE TYPE borrow_status_enum AS ENUM ('pending', 'approved', 'rejected');

-- Users Table
CREATE TABLE users (
  id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  password text NOT NULL,
  type user_type_enum NOT NULL,
  email text UNIQUE NOT NULL,
  phone text UNIQUE,
  status user_status_enum NOT NULL,
  rating float,
  last_login date,
  joining_date date NOT NULL
);

-- Students Table
CREATE TABLE students (
  id int PRIMARY KEY REFERENCES users(id),
  rollno int UNIQUE NOT NULL,
  department text NOT NULL,
  batch int NOT NULL,
  semester int NOT NULL
);

-- Teachers Table
CREATE TABLE teachers (
  id int PRIMARY KEY REFERENCES users(id),
  department text NOT NULL,
  designation text NOT NULL
);

-- Librarians Table
CREATE TABLE librarians (
  id int PRIMARY KEY REFERENCES users(id),
  admin boolean DEFAULT false
);

-- Categories Table
CREATE TABLE categories (
  id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name text UNIQUE NOT NULL,
  description text NOT NULL,
  created_at date NOT NULL
);

-- Books Table
CREATE TABLE books (
  id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  category_id int REFERENCES categories(id),
  title text NOT NULL,
  isbn text UNIQUE,
  author text NOT NULL,
  publisher text NOT NULL,
  published_year int NOT NULL,
  language text NOT NULL,
  cover_image text,
  tags text,
  storage_type storage_type_enum NOT NULL
  added_by int REFERENCES users(id),
);

-- Online Books
CREATE TABLE book_online (
  id int PRIMARY KEY REFERENCES books(id),
  address text NOT NULL,
  platform_name text NOT NULL,
  access_url text NOT NULL,
  format text NOT NULL
);

-- Offline Books
CREATE TABLE book_offline (
  id int PRIMARY KEY REFERENCES books(id),
  quantity int NOT NULL,
  address text NOT NULL,
  shelf_no text NOT NULL,
  room text NOT NULL
);

-- Borrow Table
CREATE TABLE borrow (
  id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id int REFERENCES users(id),
  book_id int REFERENCES books(id),
  request_description text,
  request_date date NOT NULL,
  return_date date,
  fine numeric DEFAULT 0,
  approved_by int REFERENCES users(id),
  approved_date date,
  return_condition text,
  status borrow_status_enum DEFAULT 'pending',
  reminder_sent boolean DEFAULT false
);

-- Fine Table
create table fines (
  id integer generated by default as identity not null,
  user_id integer null,
  borrow_id integer null,
  amount numeric not null,
  paid boolean null default false,
  paid_date date null,
  payment_method text null,
  reason text null,
  created_at date not null,
  constraint fines_pkey primary key (id),
  constraint fines_borrow_id_fkey foreign KEY (borrow_id) references borrow (id),
  constraint fines_user_id_fkey foreign KEY (user_id) references users (id) on delete CASCADE
) TABLESPACE pg_default;

-- Record Table
CREATE TABLE records (
  id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id int REFERENCES users(id),
  action text NOT NULL,
  book_id int REFERENCES books(id),
  borrow_id int REFERENCES borrow(id),
  timestamp date NOT NULL,
  ip_address text,
  device_info text,
  created_by int REFERENCES users(id),
  action_details text
);

-- Notification table for borrow requests and other system notifications
CREATE TABLE IF NOT EXISTS notifications (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    book_id INTEGER REFERENCES books(id) ON DELETE SET NULL,
    type VARCHAR(32) NOT NULL, -- e.g. 'borrow_request', 'info', etc.
    message TEXT NOT NULL,
    status VARCHAR(32) DEFAULT 'pending', -- e.g. 'pending', 'approved', 'rejected'
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Index for fast lookup by user and type
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_type ON notifications(type);
